# Generated by Django 5.2.7 on 2025-10-29 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TiebaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='分类图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '贴吧分类',
                'verbose_name_plural': '贴吧分类',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tieba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='贴吧名称')),
                ('title', models.CharField(max_length=100, verbose_name='贴吧标题')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='贴吧描述')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='tieba_avatars/', verbose_name='贴吧头像')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='tieba_banners/', verbose_name='贴吧横幅')),
                ('member_count', models.IntegerField(default=0, verbose_name='成员数')),
                ('post_count', models.IntegerField(default=0, verbose_name='帖子数')),
                ('today_post_count', models.IntegerField(default=0, verbose_name='今日帖子数')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('join_need_approval', models.BooleanField(default=False, verbose_name='加入需要审核')),
                ('post_need_approval', models.BooleanField(default=False, verbose_name='发帖需要审核')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tiebas', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('moderators', models.ManyToManyField(blank=True, related_name='moderated_tiebas', to=settings.AUTH_USER_MODEL, verbose_name='吧务团队')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiebas.tiebacategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '贴吧',
                'verbose_name_plural': '贴吧',
                'ordering': ['-member_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TiebaAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
                ('tieba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='tiebas.tieba', verbose_name='贴吧')),
            ],
            options={
                'verbose_name': '贴吧公告',
                'verbose_name_plural': '贴吧公告',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TiebaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='规则标题')),
                ('content', models.TextField(verbose_name='规则内容')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tieba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='tiebas.tieba', verbose_name='贴吧')),
            ],
            options={
                'verbose_name': '贴吧规则',
                'verbose_name_plural': '贴吧规则',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TiebaFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('tieba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='tiebas.tieba', verbose_name='贴吧')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tieba_follows', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '贴吧关注',
                'verbose_name_plural': '贴吧关注',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'tieba')},
            },
        ),
        migrations.CreateModel(
            name='TiebaMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', '普通成员'), ('moderator', '小吧主'), ('admin', '大吧主')], default='member', max_length=20, verbose_name='角色')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('active', '正常'), ('banned', '封禁'), ('left', '已退出')], default='active', max_length=20, verbose_name='状态')),
                ('level', models.IntegerField(default=1, verbose_name='贴吧等级')),
                ('experience', models.IntegerField(default=0, verbose_name='贴吧经验')),
                ('sign_in_count', models.IntegerField(default=0, verbose_name='签到次数')),
                ('last_sign_in', models.DateTimeField(blank=True, null=True, verbose_name='最后签到时间')),
                ('continuous_sign_in', models.IntegerField(default=0, verbose_name='连续签到天数')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tieba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tiebas.tieba', verbose_name='贴吧')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tieba_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '贴吧成员',
                'verbose_name_plural': '贴吧成员',
                'ordering': ['-role', '-experience', 'joined_at'],
                'unique_together': {('tieba', 'user')},
            },
        ),
    ]
