# Generated by Django 5.2.7 on 2025-10-29 04:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('level', models.IntegerField(default=1, verbose_name='等级')),
                ('experience', models.IntegerField(default=0, verbose_name='经验值')),
                ('post_count', models.IntegerField(default=0, verbose_name='发帖数')),
                ('reply_count', models.IntegerField(default=0, verbose_name='回帖数')),
                ('follow_count', models.IntegerField(default=0, verbose_name='关注数')),
                ('follower_count', models.IntegerField(default=0, verbose_name='粉丝数')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='个人简介')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='所在地')),
                ('website', models.URLField(blank=True, verbose_name='个人网站')),
                ('weibo', models.CharField(blank=True, max_length=100, verbose_name='微博')),
                ('qq', models.CharField(blank=True, max_length=20, verbose_name='QQ号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='推送通知')),
                ('private_message_notifications', models.BooleanField(default=True, verbose_name='私信通知')),
                ('show_online_status', models.BooleanField(default=True, verbose_name='显示在线状态')),
                ('show_post_count', models.BooleanField(default=True, verbose_name='显示发帖数')),
                ('allow_private_messages', models.BooleanField(default=True, verbose_name='允许私信')),
                ('theme', models.CharField(choices=[('light', '浅色'), ('dark', '深色'), ('auto', '自动')], default='light', max_length=20, verbose_name='主题')),
                ('language', models.CharField(choices=[('zh-hans', '简体中文'), ('zh-hant', '繁体中文'), ('en', 'English')], default='zh-hans', max_length=10, verbose_name='语言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户设置',
                'verbose_name_plural': '用户设置',
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='关注者')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='被关注者')),
            ],
            options={
                'verbose_name': '用户关注',
                'verbose_name_plural': '用户关注',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
